# Generated by Django 5.0.1 on 2024-01-26 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_licenseplateinfo_recognition_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplateinfo',
            name='recognition_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 23, 24, 51, 245510), verbose_name='识别时间'),
        ),
    ]
